# Generated by Django 5.2.1 on 2025-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
